# Generated by Django 4.2.6 on 2023-10-14 11:51

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='url_imagem',
            field=models.ImageField(null=True, upload_to=core.models.user_image_field),
        ),
    ]
