# Generated by Django 4.2.6 on 2023-10-14 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_conta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='agencia',
            field=models.CharField(max_length=4),
        ),
    ]
